spring:
  profiles:
    active: "@spring.profiles.active@"

---
spring:
  profiles: native
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888

---
spring:
  profiles: git
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      server:
        git:
          uri: http://192.168.0.240:9990/DevelopmentTwo/microservice/configuration.git
          username: zhaoshu
          password: 12345678

server:
  port: 8888
