spring:
  sleuth:
    sampler:
      probability: 1.0
    traceId128: true

server:
  address: localhost
  port: 6061

#we tell the Eureka Client the server url
eureka:
  client:
    serviceUrl:
      defaultZone: http://${server.address}:8761/eureka/

  # the eureka client will send heart beats every 10 seconds, default is 30 seconds
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    ipAddress: ${server.address}
    instanceId: ${server.address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG